### ISSUE TITLE
Error because of double slash at the end of domain

### ISSUE THREAD

**Issue by iandroogmans** [onlineconvert/onlineconvert-api-sdk-php#1]
When using the default ApiClient i'm getting the following error.
[404] Error connecting to the API (http://api2.online-convert.com//statuses)

I'm currently fixing this by creating an ApiClient without the end-slash in the domain.
$information_api = new InformationApi(new \SwaggerClient\ApiClient('http://api2.online-convert.com'));

It could be interesting to include a check for end-slash so you can add a domain with or without it.

**Comment by andrescevp** [comment]
We are currently working in this. Thanks for you report. :)

**Comment by andrescevp** [comment]
Fixed and closed.

https://github.com/onlineconvert/onlineconvert-api-sdk-php/commit/3c14dba16225cc039c545c5add5f2423bf7c2766
