### ISSUE TITLE
SendRequest in Client is not compatible with SendRequest in Interfaced

### ISSUE THREAD

**Issue by ashishranpara** [onlineconvert/onlineconvert-api-sdk-php#14]
Hi Qaamgo,

Ashish here.

It seems that the sendRequest function in OnlineConverterClient.php is not compatible with sendRequest function defined in its interfaced. Last parameter $headers either should be null in both or should be array in both.

Thanks,
Ashish

**Comment by online-convert** [comment]
fixed in #15
