### ISSUE TITLE
How to create job with input type = upload

### ISSUE THREAD

**Issue by unlight** [onlineconvert/onlineconvert-api-sdk-php#3]
Is it possible to create a job with type = upload (local file)?

Now, to do it i must create empty job: http://api.online-convert.com/#file_upload
Then add files to job.

I'm trying to do:

``` js
{
    "input": [{
        "type": "upload",
        "filename": "image1"
    }],
    "conversion": [{
        "target": "png"
    }],
   "image1": {"what is here?"}
}
```

`input`, `conversion` should be form fields (serialized?) or what?
Could you provide example?

**Comment by borjaeu** [comment]
In order to upload files directly to the server. It is needed to know in advance the server assigned to the job.

The input must no be specified when creating the job, once the job has been created the information for the job will show the server assigned and the job id.

The file must be POST to this server 

```
 POST https://<server>/upload-file/<job_id> HTTP/1.1
 X-Oc-Api-Key: <api_key>

------WebKitFormBoundaryePkpFF7tjBAqx29L
Content-Disposition: form-data; name="file"; filename="whatever.png"
Content-Type: image/png

... contents of file goes here ...
------WebKitFormBoundaryePkpFF7tjBAqx29L-
```

Once the file has been uploaded to the server the job will show the uploaded file with the "upload" type.

**Comment by unlight** [comment]
Thanks for response. Maybe I explained it wrong.
But the idea was to create a job by SINGLE request for local file.

``` sh
POST /jobs HTTP/1.1
Host: https://api2.online-convert.com
X-Oc-Api-Key: <your API key here>
Content-Type: application/json
{
    "input": [{
        "type": "remote",
        "source": "http:\/\/bit.ly\/b2dlVA"
    }],
    "conversion": [{
        "target": "png"
    }]
}
```

Example above will create a job for remote file.
I want same for local file, is it possible?

**Comment by lombartec** [comment]
Hello @unlight, creating a Job and uploading the input from a local file in the same request is **not possible** at the moment. 

As @borjaeu explained, we first need to know the server assigned to the job to upload the file directly to it via the post request.
