### ISSUE TITLE
conversion hangs

### ISSUE THREAD

**Issue by onabil** [onlineconvert/onlineconvert-api-sdk-php#31]
Hi,
I'm trying to use the api2 via php sdk
the php page hangs forever here is my code:

> require_once 'lib/vendor/autoload.php';
>         $config = new \OnlineConvert\Configuration();
>         $config->setApiKey('main', OC_API_KEY);
>         $config->downloadFolder = __DIR__ . '/downloads';
>         $client = new \OnlineConvert\Client\OnlineConvertClient($config, 'main');
>         $syncApi = new \OnlineConvert\Api($client);
>         $syncJob = [
>             'input' => [
>                 [
>                     'type' => \OnlineConvert\Endpoint\InputEndpoint::INPUT_TYPE_UPLOAD,
>                     'source' => $filePath
>                 ],
>             ],
>             'conversion' => [
>                 [
>                     'target' => 'pdf'
>                 ],
>             ]
>         ];
>         $outputEndpoint = $syncApi->getOutputEndpoint();
>         $job = $syncApi->postFullJob($syncJob)->getJobCreated();
>         $outputEndpoint->downloadOutputs($job);

OC_API_KEY is a constant, and $filePath is a function parameter.
It seems to me that the process hangs on row:

> $job = $syncApi->postFullJob($syncJob)->getJobCreated();

Checking the jobs list (tried in the sandbox: https://apiv2.online-convert.com/docs/getting_started/sandbox.html#!/Jobs/get_jobs)
I see the status: 

> "status": {
>       "code": "incomplete",
>       "info": "Missing information to run the job."
>     },

Am I missing something?
Many thanks,

**Comment by jensbierkandt** [comment]
Your code looks good to me. I have added the following lines on top of your source code:

```php
<?php
define('OC_API_KEY', '<your API key here>');
define('DIR', '/home/test/api2sdktest/');
$filePath = '/home/test/test.txt';
```
Then running your source code succeeded. Do you see any errors when you run your code on the command line? Maybe your file is quite large and needs time to upload?

> $filePath is a function parameter

I used a string, can you try as well and see if you succeed?

**Comment by onabil** [comment]
Thanks @schtorch , as I'm still having this issue, I created a new script (oc_check.php) to isolate the conversion:
```php
<?php

define('OC_API_KEY', '<your API key here>');
define('DIR', '/tmp');
$filePath = '/tmp/test.txt';
file_put_contents($filePath, "here is my text");
require_once 'lib/vendor/autoload.php';
$config = new \OnlineConvert\Configuration();
$config->setApiKey('main', OC_API_KEY);
$config->downloadFolder = DIR;
$client = new \OnlineConvert\Client\OnlineConvertClient($config, 'main');
$syncApi = new \OnlineConvert\Api($client);
$syncJob = [
    'input' => [
        [
            'type' => \OnlineConvert\Endpoint\InputEndpoint::INPUT_TYPE_UPLOAD,
            'source' => $filePath
        ],
    ],
    'conversion' => [
        [
            'target' => 'pdf'
        ],
    ]
];
$outputEndpoint = $syncApi->getOutputEndpoint();
var_dump($syncApi);
$api = $syncApi->postFullJob($syncJob);
$job = $api->getJobCreated();
$outputEndpoint->downloadOutputs($job);
```
I defined OC_API_KEY with my correct api key.
the process hangs on: \OnlineConvert\Endpoint\JobsEndpoint::waitStatus as it continues to receive status:incomplete, with info: Missing information to run the job.
My "php --version" output is:
```
PHP 5.6.31 (cli) (built: Jul 10 2017 11:54:08) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
```
You will find attached  the *$syncApi* dump and my composer.lock content:
[syncApi.txt](https://github.com/onlineconvert/onlineconvert-api-sdk-php/files/1590995/syncApi.txt)
[composer.txt](https://github.com/onlineconvert/onlineconvert-api-sdk-php/files/1590998/composer.txt)

Many thanks,

**Comment by online-convert** [comment]
Hi @onabil,

please excuse the waiting time.

We have once again investigated in your issue. We have tried the script from your last example with the given composer file. The conversion was completed without any issues.

The "missing information to run the job" message most likely comes from a missing input file. So is there perhaps an issue with your upload? Can you perhaps try a conversion with a remote input?

**Comment by onabil** [comment]
Hi @online-convert,
as I saw the last commit (Added HTTP Response in RequestException) I updated and retried using the upload method but it still doesn't work.
Then I tried the **remote input method** and **it works**.
I'll change my code to use the remote working method.
Many thanks,
