### ISSUE TITLE
Automated tests are busted to hell

### ISSUE THREAD

**Issue by hopeseekr** [onlineconvert/onlineconvert-api-sdk-php#50]
> .......PHP Fatal error:  Declaration of SebastianBergmann\Comparator\DOMNodeComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false) must be compatible with SebastianBergmann\Comparator\ObjectComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false, array &$processed = Array) in /code/contribs/onlineconvert-api-sdk-php/vendor/sebastian/comparator/src/DOMNodeComparator.php on line 48

But don't worry, i'm fixing this right now!

**Comment by online-convert** [comment]
Hi,
thanks for the hint!
We have created a new release 3.0. This should fix the phpunit tests for php 7.1 - 7.4
The composer.lock was removed because it should not be there at all.

If you want you can try the tests there again. They all have passed the travis build.
