### ISSUE TITLE
PHP 8 Support?

### ISSUE THREAD

**Issue by HKandulla** [onlineconvert/onlineconvert-api-sdk-php#58]
Hi, could you please give us a rough idea when PHP 8 will be supported?

Thanks, Hannes

**Comment by online-convert** [comment]
Hi @HKandulla

thank you for your request. There is a new release planned in the next few days to support php8.

**Comment by HKandulla** [comment]
Hi @online-convert ,
great! Thanks. Best, Hannes

**Comment by online-convert** [comment]
Hi @HKandulla ,
we just released the version 3.1.2 with php8 support. Thank you for your patience.
