### ISSUE TITLE
Please convert to the latest api url api.api2convert.com/v2

### ISSUE THREAD

**Issue by frankdekkers** [onlineconvert/onlineconvert-api-sdk-php#67]
Hello, we just got an email from onlineconvert regarding the change the used API URL to the encrypted, new url / api.

We are using your services extensively with 3 user accounts and converting 150+ documents daily.

Could you please update this PHP API SDK to work with the latest API URL? Also, by default, it might be better to use the https version of your API.

Encrypted, old domain, deprecated: (this is the URL that is optionally available within your SDK)
https://api2.online-convert.com/ <https://api2.online-convert.com/>...

Encrypted, new domain (explanation below): (this is the URL that should become available within your SDK)
https://api.api2convert.com/v2/ <https://api.api2convert.com/v2/>...

Your help / support is greatly appreciated. Kind regards!

**Comment by online-convert** [comment]
We have just released version 3.1.8 of the SDK. This latest release addresses the deprecation concerns you mentioned:

* Encryption by Default: Encryption is now enabled by default.
* New Domain: The API endpoint has been updated to api2convert.

To resolve the deprecation issues, please update your SDK to version 3.1.8
